name: Deploy Swagger to GitHub Pages

# Trigger the action on push and on a schedule (e.g., every 5 minutes)
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/1 * * * *'  # Runs every 5 minutes (change this to your desired frequency)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout swagger-docs-auctions Repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'hrhm47'
          git config --global user.email 'haseebr470@gmail.com'

      - name: Clone pwp_ah Repo (tonttu-hypermedia)
        run: |
          git clone https://x-access-token:${{ secrets.MY_GITHUB_PAT }}@github.com/hrhm47/tonttu-hypermedia.git

      - name: Copy Swagger Docs
        run: |
          echo "Copying Swagger docs..."
          rm -rf swagger-docs-auctions/docs/components
          rm -rf swagger-docs-auctions/docs/paths
          cp -r tonttu-hypermedia/server/docs/components swagger-docs-auctions/docs/
          cp -r tonttu-hypermedia/server/docs/paths swagger-docs-auctions/docs/
          cp tonttu-hypermedia/server/docs/swagger.yaml swagger-docs-auctions/docs/

      - name: Commit and Push Changes
        run: |
          cd swagger-docs-auctions
          git add .
          git commit -m "Update Swagger documentation from tonttu repo" || echo "No changes to commit"
          git push origin main || echo "No changes to push"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token for deployment
          publish_dir: ./swagger-docs-auctions/docs
          publish_branch: main
